# --------------------------------------------------
# Theme Settings
# --------------------------------------------------
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
plugins:
  - jekyll-include-cache
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Options: "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
baseurl: "/cryptonavigator.com"         # Subpath of your site, e.g., "/blog"
exclude:
  - CHANGELOG.md
layout: "default"
# --------------------------------------------------
# Site Settings
# --------------------------------------------------
# _config.yml
repository: "thechadgreat88/cryptonavigator.com"
locale: "en-US"
rtl: false                     # Set to true for right-to-left languages
plugins:
  - jekyll-include-cache
title_separator: "-"
timezone: "America/Los_Angeles"
subtitle: "Your trusted guide in the ever-evolving digital currency landscape."
description: "A comprehensive guide to navigating the world of cryptocurrencies, providing insights, analysis, and resources for enthusiasts and investors alike."
keywords: "cryptocurrency, blockchain, digital currency, bitcoin, ethereum, altcoins, trading, investing" 
url: "https://Thechadgreat88.github.io/cryptonavigator.com"
 # Base hostname & protocol, e.g., "https://mmistakes.github.io"
masthead_title: ""                          # Overrides website title in masthead (leave empty if not needed)
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: false
copyright: "cryptonavigator"
copyright_url: "/cryptonavigator"
# --------------------------------------------------
# Comments and Third-party Integrations
# --------------------------------------------------
comments:
  provider: false   # Set to "disqus", "facebook", "utterances", etc. for enabled comment systems
  # For example, to use Disqus:
  # disqus:
  #   shortname: "your-disqus-shortname"

reCaptcha:
  siteKey: ""
  secret: ""

atom_feed:
  path: feed.xml
  hide: false

# --------------------------------------------------
# Search and SEO
# --------------------------------------------------
search: false
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: false

algolia:
  application_id: ""
  index_name: ""
  search_only_api_key: ""
  powered_by: true

google:
  search_engine_id: ""
  instant_search: false

google_site_verification: ""
bing_site_verification: ""
naver_site_verification: ""
yandex_site_verification: ""
baidu_site_verification: ""

# --------------------------------------------------
# Social Sharing
# --------------------------------------------------
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""  # Default Open Graph image

social:
  type: "Person"  # Options: Person, Organization
  name: ""
  links: []       # Add social links if needed

# --------------------------------------------------
# Analytics
# --------------------------------------------------
analytics:
  provider: false   # Options: "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: ""
    anonymize_ip: false

# --------------------------------------------------
# Site Author
# --------------------------------------------------
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person."
  location: "Somewhere"
  email: ""
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# --------------------------------------------------
# Site Footer
# --------------------------------------------------
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: ""
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: ""
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: ""
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"


# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
